@startuml

title Этапы разработки крупной функциональности системы

Требования: Определение бизнес-постановок\nи требований приемки работ
Проектирование: Проработка архитектуры\nбудущего решения
Разработка: Непосредственная\nреализация решения
Тестирование: Проверка решения\nсогласно требованиям
Демо: Представление результатов\nработы для Stakeholders
Release: Выкатка решения на\nпромышленные стенды
Notes: Объявление о релизе\nновой функциональности

[*] -right-> Требования  

Требования  -right-> Проектирование 

Проектирование  -right-> Разработка

Разработка  -down-> Тестирование

Тестирование  -left-> Демо

Демо  -left-> Release

Release  -left-> Notes

Notes  -left-> [*]

@enduml