@startuml "Интеграция севера и тикет системы (БП)"

participant Студент 
participant LMS
participant Север
participant КС

autonumber
Студент -> LMS : написал нам сообщение
LMS -> Север : отправляем запрос в Север
alt#Gold Вероятность выше 0.33
  alt  Вероятность от 0.33 до границы threshold
    Север -> LMS : Присваиваем тег "ВозвратML"
    alt #Pink Если тикет не про возврат
      Север -> LMS : Ответ
      LMS <- КС  : Присваиваем\nтег "Ошибка ML"
    end
  else Вероятность равно threshold и выше
    Север -> LMS : Присваиваем тег "ВозвратML"
    LMS -> LMS : Перекидываем тикет на группу "Возвраты"
    alt#Gold #Pink Если тикет не про возврат
      Север -> LMS : Ответ
      LMS -> КС  : Присваиваем\nтег "Ошибка ML"
    end
  end
else #Pink Вероятность  ниже 0.33
  Север -> LMS : Ответ
  LMS -> КС : Никакой тег не присваиваем 
end

LMS -> КС : Группа возвратов пытается удержать студента
alt#Gold #Pink Студент не был удержан
  КС -> LMS : Проставляем тег "Fail"
else #LightGreen
  КС -> LMS : Проставляем тег "Saved"
end

@enduml